### ISSUE TITLE
Dataset availability and network input channels count 

### ISSUE THREAD

**Issue by ArmanChopikyan** [CQFIO/FastImageProcessing#1]
Hi!
Is the dataset on which You trained Your network available publicly, or You can provide it?
And why is your single network input has unusual channels count(10 +3 instead of 3 ), what does additional 10 channels with default initialized const values do, or contribute to?
I’m looking forward to your reply.

**Comment by CQFIO** [comment]
If you want to get the dataset I trained on, please send an email to me at chenqifeng22@gmail.com.

The single network approximates 10 image operators in a network. The other 10 channels form a hot vector to indicate which image operator to perform.

**Comment by ArmanChopikyan** [comment]
Thank you for your fast response, I send you an email.
