### ISSUE TITLE
[Initializer]: What is the significance?

### ISSUE THREAD

**Issue by nrupatunga** [CQFIO/FastImageProcessing#6]
Hi All, 

Does anyone understand the significance of `identity_initializer`?

```
def identity_initializer():
    def _initializer(shape, dtype=tf.float32, partition_info=None):
        array = np.zeros(shape, dtype=float)
        cx, cy = shape[0]//2, shape[1]//2
        for i in range(np.minimum(shape[2],shape[3])):
            array[cx, cy, i, i] = 1
        return tf.constant(array, dtype=dtype)
    return _initializer
```

Any intuition is much appreciated.!

**Comment by CQFIO** [comment]
The identity initialization is used to stabilize the training. Initially, the network basic performs identity mapping from the input image to the output.

**Comment by nrupatunga** [comment]
Thank you for your reply. That's pretty neat trick!

One more question, if the filter is of shape `(3, 3, 3, 24)`, here I see from the above code only, 
`array(1, 1, 0:3, 0:3]` is set, Is there any reason you choose (`np.minimum(shape[2],shape[3])`) the first three (3, 3, 3) out of 24 filters to be identity filter and rest as zero.? or is it random?

**Comment by CQFIO** [comment]
@nrupatunga In your case, I just set the first 3 filters to be identity mapping and the rest to be zeros.

**Comment by nrupatunga** [comment]
ah! my bad. thank you :)
